# Generated by Django 6.0.5 on 2026-05-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guru',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='guru/'),
        ),
        migrations.AddField(
            model_name='siswa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='siswa/'),
        ),
    ]
