# Generated by Django 6.0.5 on 2026-06-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_berita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('gambar', models.ImageField(upload_to='galeri/')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
