# Generated by Django 6.0.5 on 2026-06-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_guru_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilSekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sekolah', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='profil/')),
                ('alamat', models.TextField()),
                ('telepon', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('visi', models.TextField()),
                ('misi', models.TextField()),
            ],
        ),
    ]
