# Generated by Django 6.0.5 on 2026-07-02 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_profilsekolah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='kelas',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tingkat', models.CharField(choices=[('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], max_length=5)),
                ('nama', models.CharField(max_length=30)),
                ('jurusan', models.CharField(max_length=50)),
                ('wali_kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.guru')),
            ],
        ),
    ]
