# Generated by Django 6.0.5 on 2026-07-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_jadwal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TahunAjaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.CharField(max_length=20)),
                ('semester', models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], max_length=10)),
                ('aktif', models.BooleanField(default=False)),
            ],
        ),
    ]
