# Generated by Django 6.0.5 on 2026-07-07 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_tahunajaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwal',
            name='tahun_ajaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.tahunajaran'),
        ),
    ]
