# Generated by Django 6.0.5 on 2026-07-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_jadwal_tahun_ajaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='guru',
            name='status',
            field=models.CharField(choices=[('Menunggu', 'Menunggu'), ('Aktif', 'Aktif'), ('Ditolak', 'Ditolak')], default='Menunggu', max_length=20),
        ),
        migrations.AddField(
            model_name='siswa',
            name='status',
            field=models.CharField(choices=[('Menunggu', 'Menunggu'), ('Aktif', 'Aktif'), ('Ditolak', 'Ditolak')], default='Menunggu', max_length=20),
        ),
    ]
