# Generated by Django 6.0.5 on 2026-07-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_guru_status_siswa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='nis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
