# Generated by Django 6.0.5 on 2026-07-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_siswa_nis'),
    ]

    operations = [
        migrations.AddField(
            model_name='guru',
            name='nip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
