# Generated by Django 6.0.5 on 2026-07-29 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_convert_kelas_to_foreignkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siswa', to='web.kelas'),
        ),
    ]
