# Generated by Django 6.0.5 on 2026-07-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu'), ('aktif', 'Aktif'), ('ditolak', 'Ditolak')], default='pending', max_length=20),
        ),
    ]
