# Generated by Django 6.0.5 on 2026-06-24 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0004_galeri'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mata_pelajaran', models.CharField(max_length=100)),
                ('tugas', models.IntegerField()),
                ('uts', models.IntegerField()),
                ('uas', models.IntegerField()),
                ('nilai_akhir', models.FloatField(blank=True, null=True)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.guru')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.siswa')),
            ],
        ),
    ]
