# Generated by Django 6.0.5 on 2026-06-25 00:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0001_initial'),
        ('web', '0006_guru_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Hadir', 'Hadir'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Alfa', 'Alfa')], max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.siswa')),
            ],
        ),
    ]
