# Generated by Django 6.0.5 on 2026-06-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0002_absensi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('mata_pelajaran', models.CharField(max_length=100)),
                ('kelas', models.CharField(max_length=20)),
                ('deskripsi', models.TextField()),
                ('file', models.FileField(upload_to='materi/')),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
