# Generated by Django 6.0.5 on 2026-06-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0003_materi'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='mata_pelajaran',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
