# Generated by Django 6.0.5 on 2026-06-26 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0004_absensi_mata_pelajaran'),
        ('web', '0007_profilsekolah'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('mata_pelajaran', models.CharField(max_length=100)),
                ('kelas', models.CharField(max_length=20)),
                ('deskripsi', models.TextField()),
                ('file_tugas', models.FileField(blank=True, null=True, upload_to='tugas/')),
                ('deadline', models.DateTimeField()),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PengumpulanTugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_jawaban', models.FileField(upload_to='jawaban/')),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('nilai', models.IntegerField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.siswa')),
                ('tugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.tugas')),
            ],
        ),
    ]
