# Generated by Django 6.0.5 on 2026-06-26 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0005_tugas_pengumpulantugas'),
        ('web', '0007_profilsekolah'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengumpulantugas',
            name='guru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.guru'),
        ),
        migrations.AddField(
            model_name='pengumpulantugas',
            name='status',
            field=models.CharField(choices=[('Belum Dinilai', 'Belum Dinilai'), ('Sudah Dinilai', 'Sudah Dinilai')], default='Belum Dinilai', max_length=30),
        ),
        migrations.AddField(
            model_name='pengumpulantugas',
            name='tanggal_dinilai',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
