# Generated by Django 6.0.5 on 2026-06-27 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0006_pengumpulantugas_guru_pengumpulantugas_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ujian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('mata_pelajaran', models.CharField(max_length=100)),
                ('kelas', models.CharField(max_length=20)),
                ('jurusan', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=20)),
                ('jenis', models.CharField(choices=[('UTS', 'UTS'), ('UAS', 'UAS')], max_length=10)),
                ('durasi', models.IntegerField(help_text='Menit')),
                ('tanggal_mulai', models.DateTimeField()),
                ('tanggal_selesai', models.DateTimeField()),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.TextField()),
                ('pilihan_a', models.CharField(max_length=300)),
                ('pilihan_b', models.CharField(max_length=300)),
                ('pilihan_c', models.CharField(max_length=300)),
                ('pilihan_d', models.CharField(max_length=300)),
                ('jawaban_benar', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('poin', models.IntegerField(default=1)),
                ('ujian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soal', to='akademik.ujian')),
            ],
        ),
    ]
