# Generated by Django 6.0.5 on 2026-06-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0007_ujian_soal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soal',
            options={'ordering': ['nomor']},
        ),
        migrations.AddField(
            model_name='soal',
            name='nomor',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soal',
            name='pembahasan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
