# Generated by Django 6.0.5 on 2026-06-27 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0008_alter_soal_options_soal_nomor_soal_pembahasan'),
        ('web', '0007_profilsekolah'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasilUjian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.FloatField(default=0)),
                ('benar', models.IntegerField(default=0)),
                ('salah', models.IntegerField(default=0)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('selesai', models.BooleanField(default=False)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.siswa')),
                ('ujian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.ujian')),
            ],
        ),
    ]
