# Generated by Django 6.0.5 on 2026-06-27 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0009_hasilujian'),
    ]

    operations = [
        migrations.CreateModel(
            name='JawabanSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('benar', models.BooleanField(default=False)),
                ('hasil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.hasilujian')),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.soal')),
            ],
        ),
    ]
