# Generated by Django 6.0.5 on 2026-07-07 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0010_jawabansiswa'),
        ('web', '0010_tahunajaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujian',
            name='tahun_ajaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='web.tahunajaran'),
        ),
    ]
