# Generated by Django 6.0.5 on 2026-07-07 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0011_ujian_tahun_ajaran'),
        ('web', '0010_tahunajaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='tahun_ajaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='web.tahunajaran'),
        ),
        migrations.AddField(
            model_name='materi',
            name='tahun_ajaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='web.tahunajaran'),
        ),
        migrations.AddField(
            model_name='nilai',
            name='tahun_ajaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='web.tahunajaran'),
        ),
        migrations.AddField(
            model_name='tugas',
            name='tahun_ajaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='web.tahunajaran'),
        ),
    ]
