# Generated by Django 6.0.5 on 2026-08-13 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0013_delete_data_alter_kelas_fk'),
        ('web', '0016_alter_siswa_kelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugas',
            name='guru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='web.guru'),
        ),
    ]
