# Generated by Django 6.0.5 on 2026-08-13 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0014_tugas_guru'),
        ('web', '0016_alter_siswa_kelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='guru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='web.guru'),
        ),
        migrations.AddField(
            model_name='ujian',
            name='guru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='web.guru'),
        ),
    ]
